version: '3.9'


services:
  redis:
    image: redis:7.0.5
    command: >
      redis-server --requirepass pass123
      --appendonly yes
      --appendfsync everysec
      --save 900 1
      --save 300 10
      --save 60 10000
      --dir /data
      --dbfilename dump.rdb
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  app:
    image: nlema2411/url-shortener:demo
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: pass123
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana:10.0.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  redis-data:
    driver: local
  grafana-storage:

networks:
  default:
    driver: bridge

