version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: temp-password
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass temp-password
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: temp-password

networks:
  default:
    driver: bridge
