apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  namespace: default
  labels:
    app: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: nlema2411/url-shortener:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_REDIS_PASSWORD
              value: "pass123"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  namespace: default
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80       # El puerto en el que el servicio estará disponible
      targetPort: 8080 # El puerto en el que la aplicación escucha dentro del contenedor
  type: LoadBalancer  # Puedes cambiar a NodePort si estás usando Minikube